<?xml version="1.0"?>
<definitions xmlns:tns="http://example.com/titles/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:defs="http://example.com/titles/definitions" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://example.com/titles/service" name="MYRF">
    <types>
		<element minOccurs="0" name="MYRF" form="unqualified" nillable="true" type="string"/>
    </types>
    <message name="MYRF">
        <part name="MYRF" type="ns0:AccountingPeriodRequest"/>
    </message>
	<portType name="MYRFPortType">
		<operation name="MYRF">
        </operation>
	</portType>
	<binding name="MYRFSoapBinding" type="tns:MYRFPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="MYRF">
			<soap:operation soapAction="http://example.com/MYRF"/>
		</operation>
	</binding>
	<service name="MYRFService">
		<documentation>My first service</documentation>
		<port name="MYRFPort" binding="tns:MYRFSoapBinding">
			<soap:address location="http://example.com/MYRF"/>
		</port>
	</service>
</definitions>

